import { createI18n } from 'vue-i18n'

export const supportedLocales = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'fr', label: 'Français', short: 'FR' },
  { code: 'ar', label: 'العربية', short: 'AR' },
]

const en = {
  common: { workspace: 'Workspace', copy: 'Copy', active: 'Active', draft: 'Draft', live: 'Live', questions: 'questions', calls: 'calls', successful: 'successful', total: 'total', signOut: 'Sign out', language: 'Language' },
  error: { request: 'Request failed.' },
  page: { builder: 'Classifier builder', keys: 'API keys', analytics: 'Usage analytics', archive: 'Archive' },
  auth: {
    opening: 'Opening Jev-It Studio…', overline: 'Your classifier workspace', title: 'Build decisions', titleEm: 'through conversation.',
    description: 'Sign in to keep your classifiers, deployments, API keys, quotas, and usage analytics inside your own private workspace.',
    continueGoogle: 'Continue with Google', mongoMissing: 'MongoDB is not connected.', googleMissing: 'Google SSO is not configured.', check: 'Check configuration',
    freeClassifiers: '5 classifiers on Free', monthlyCalls: '1,000 monthly JEV calls', privateWorkspace: 'Private by workspace',
  },
  nav: { newClassifier: 'New classifier', classifiers: 'Your classifiers', empty: 'Your first classifier will appear here.', freePlan: 'Free plan', archived: 'Archived classifiers' },
  setup: { title: 'Connect MongoDB', titleEm: 'to begin.', description: 'Jev-It Studio stores classifier drafts, conversations, deployments, and hashed API keys in MongoDB.', check: 'Check connection' },
  builder: {
    overline: 'Build with Luna', title: 'Describe the decision.', description: 'Your assistant will turn the need into atomic, typed JEV questions.', architect: 'JEV Architect', you: 'You',
    placeholder: 'Describe what the classifier should decide…', lowReasoning: 'low reasoning', missingKey: 'Add OPENAI_API_KEY to .env', thinking: 'Thinking…', send: 'Send',
    liveDraft: 'Live draft', updates: 'Updates as you chat', classifierName: 'Classifier name', purposePending: 'The purpose will take shape as the conversation continues.',
    questionsPending: 'Your typed questions will appear here as the intent becomes clear.', needsDetail: 'Keep chatting—the classifier still needs detail.', ready: 'Ready for your review.', creating: 'Creating…', create: 'Create classifier',
  },
  classifier: {
    productionVersion: 'Production · v{version}', undeployed: 'Undeployed draft', noDescription: 'No description yet.', configure: 'Configure', test: 'Test', deploy: 'Deploy', api: 'API',
    identity: 'Identity', identityHelp: 'The human-readable details for this classifier.', name: 'Name', description: 'Description', contentLanguage: 'Classifier language', contentLanguageHelp: 'Builder output and JEV evaluation instructions follow this language.', autoLanguage: 'Automatic / multilingual',
    questions: 'Questions', questionsHelp: 'Each question is evaluated independently against the same state.', addQuestion: 'Add question', removeQuestion: 'Remove question', instructions: 'Instructions', choiceOptions: 'Choice options', addOption: 'Add option', scoreLevels: 'Ordered score levels', addLevel: 'Add level',
    id: 'Classifier ID', draftQuestions: 'Draft questions', production: 'Production', notDeployed: 'Not deployed', saving: 'Saving…', saveDraft: 'Save draft', saveHelp: 'Saving does not affect production until you deploy.',
    archive: 'Archive classifier', archiveConfirm: 'Archive “{name}”? Its production endpoint will stop immediately, but versions and analytics will be preserved.', archivedNotice: 'Classifier archived',
  },
  archive: {
    overline: 'Classifier lifecycle', title: 'Archived classifiers', description: 'Archived classifiers stop accepting API calls and no longer count toward your plan limit.', empty: 'No archived classifiers.', archivedOn: 'Archived {date}', restore: 'Restore', restoring: 'Restoring…', delete: 'Delete permanently', deleteConfirm: 'Permanently delete “{name}”? Versions and configuration cannot be recovered. Historical aggregate analytics will remain.', deleted: 'Classifier permanently deleted', restored: 'Classifier restored',
  },
  actions: { deploying: 'Deploying…', saveFirst: 'Save draft first', deployDraft: 'Deploy draft', upToDate: 'Up to date', copied: 'Copied to clipboard', created: 'Classifier created', saved: 'Draft saved' },
  testing: { overline: 'Ephemeral test bench', title: 'Try real states.', description: 'Test one state, or separate multiple examples with a line containing ---. Nothing is saved.', placeholder: 'Paste a state for this classifier to evaluate…\n\n---\n\nAdd another state…', running: 'Running JEV…', run: 'Run test', emptyTitle: 'No results yet', emptyDescription: 'Run the draft against real examples before deploying it.', state: 'State {number}', confidence: '{value}% confidence', raw: 'Raw JEV response', rawHelp: 'Complete, unmodified JSON', copyJson: 'Copy JSON', trueValue: '{value}% true' },
  deployment: { overline: 'Production control', live: 'Version {version} is live.', empty: 'Nothing deployed yet.', description: 'Deployments are immutable snapshots. Editing your draft never changes the active production classifier.', deployCurrent: 'Deploy current draft', history: 'History', versions: 'Available versions', versionsHelp: 'Select any previous snapshot to roll production back.', versionMeta: '{count} questions · {date}', activate: 'Activate', none: 'Your first deployment will appear here.', activated: 'Version {version} is now active', existingActivated: 'Existing version {version} activated', already: 'Draft is already deployed', new: 'New version deployed' },
  api: { overline: 'Production endpoint', title: 'One state in.', titleEm: 'Typed answers out.', description: 'Use the managed endpoint, or export the complete deployed structure and call TypeSafe directly. Both examples use the active immutable snapshot.', studio: 'Through Jev-It Studio', studioHelp: 'Send only the classifier ID and state. The backend resolves the active deployment.', copyRequest: 'Copy request', direct: 'Direct to TypeSafe', directHelp: 'A portable request containing the exact questions from deployed version {version}.', copyInput: 'Copy input JSON', copyCurl: 'Copy cURL', deployToExport: 'Deploy the classifier to generate a portable JEV request.', activeSnapshot: 'Active snapshot:', snapshot: 'Version {version}, deployed {date}', deployBefore: 'Deploy this classifier before calling the endpoint.', exampleState: 'The state you want JEV to evaluate' },
  keys: { overline: 'Project access', title: 'API keys', description: 'Keys authenticate calls to your deployed classifiers. JEV and OpenAI credentials always remain server-side.', production: 'Production key', none: 'No active key', created: 'Created {date}', generateHelp: 'Generate a key to call /api/classify.', shownNow: 'Copy this key now—it won’t be shown again.', hashed: 'Stored as a SHA-256 hash', rotate: 'Rotate key', generate: 'Generate key', revoke: 'Revoke', revokeConfirm: 'Revoke the active API key? Existing integrations will stop working.', revoked: 'API key revoked', shownOnce: 'Shown once', shownOnceHelp: 'The plaintext secret is returned only when it is generated.', hashedAtRest: 'Hashed at rest', hashedAtRestHelp: 'MongoDB stores a one-way SHA-256 digest, never the original key.', instantRotation: 'Instant rotation', instantRotationHelp: 'Rotating revokes the old key before creating the replacement.' },
  analytics: { mine: 'My workspace', platform: 'Jev-It platform', admin: 'Admin view', last30: 'Last 30 days · {scope}', platformTitle: 'The whole platform.', workspaceTitle: 'Usage, at a glance.', platformDescription: 'Aggregate activity across every Jev-It workspace and classifier.', workspaceDescription: 'Every playground and production call, without storing states or model responses.', monthlyQuota: 'Monthly quota', resets: 'Resets {date}', footprint: 'Platform footprint', workspaces: 'workspaces', registeredUsers: '{count} registered user | {count} registered users', calculating: 'Calculating usage…', totalCalls: 'Total calls', playgroundApi: 'Playground + API', successRate: 'Success rate', failed: '{count} failed', medianLatency: 'Median latency', classifiers: 'Classifiers', activeFree: 'Active on Free', platformCalls: 'Platform calls', allSources: 'All sources', accounts: 'Accounts', callsOverTime: 'Calls over time', daily: 'Daily activity', timelineEmpty: 'Calls will appear here as you test and use deployed classifiers.', breakdown: 'Breakdown', byClassifier: 'By classifier', activityEmpty: 'No classifier activity yet.', tenants: 'Tenants', byWorkspace: 'By workspace', totalLabel: '{count} total', workspacesEmpty: 'No workspaces yet.', rowMeta: '{successes} successful · {latency} ms avg', workspaceMeta: '{plan} · {classifiers} classifiers · {successes} successful' },
}

const fr = {
  common: { workspace: 'Espace de travail', copy: 'Copier', active: 'Active', draft: 'Brouillon', live: 'En ligne', questions: 'questions', calls: 'appels', successful: 'réussis', total: 'total', signOut: 'Se déconnecter', language: 'Langue' },
  error: { request: 'La requête a échoué.' },
  page: { builder: 'Créateur de classificateur', keys: 'Clés API', analytics: 'Analyse d’utilisation', archive: 'Archives' },
  auth: { opening: 'Ouverture de Jev-It Studio…', overline: 'Votre espace de classificateurs', title: 'Créez vos décisions', titleEm: 'par la conversation.', description: 'Connectez-vous pour conserver vos classificateurs, déploiements, clés API, quotas et analyses dans votre espace privé.', continueGoogle: 'Continuer avec Google', mongoMissing: 'MongoDB n’est pas connecté.', googleMissing: 'Google SSO n’est pas configuré.', check: 'Vérifier la configuration', freeClassifiers: '5 classificateurs en offre gratuite', monthlyCalls: '1 000 appels JEV par mois', privateWorkspace: 'Privé par espace de travail' },
  nav: { newClassifier: 'Nouveau classificateur', classifiers: 'Vos classificateurs', empty: 'Votre premier classificateur apparaîtra ici.', freePlan: 'Offre gratuite', archived: 'Classificateurs archivés' },
  setup: { title: 'Connectez MongoDB', titleEm: 'pour commencer.', description: 'Jev-It Studio stocke les brouillons, conversations, déploiements et clés API hachées dans MongoDB.', check: 'Vérifier la connexion' },
  builder: { overline: 'Créer avec Luna', title: 'Décrivez la décision.', description: 'Votre assistant transformera le besoin en questions JEV atomiques et typées.', architect: 'Architecte JEV', you: 'Vous', placeholder: 'Décrivez ce que le classificateur doit décider…', lowReasoning: 'raisonnement faible', missingKey: 'Ajoutez OPENAI_API_KEY dans .env', thinking: 'Réflexion…', send: 'Envoyer', liveDraft: 'Brouillon en direct', updates: 'Se met à jour pendant l’échange', classifierName: 'Nom du classificateur', purposePending: 'L’objectif se précisera au fil de la conversation.', questionsPending: 'Vos questions typées apparaîtront ici.', needsDetail: 'Continuez l’échange — il manque encore des précisions.', ready: 'Prêt pour votre validation.', creating: 'Création…', create: 'Créer le classificateur' },
  classifier: { productionVersion: 'Production · v{version}', undeployed: 'Brouillon non déployé', noDescription: 'Aucune description.', configure: 'Configurer', test: 'Tester', deploy: 'Déployer', api: 'API', identity: 'Identité', identityHelp: 'Les informations lisibles de ce classificateur.', name: 'Nom', description: 'Description', contentLanguage: 'Langue du classificateur', contentLanguageHelp: 'Les réponses du créateur et les instructions JEV suivent cette langue.', autoLanguage: 'Automatique / multilingue', questions: 'Questions', questionsHelp: 'Chaque question est évaluée indépendamment sur le même état.', addQuestion: 'Ajouter une question', removeQuestion: 'Supprimer la question', instructions: 'Instructions', choiceOptions: 'Options de choix', addOption: 'Ajouter une option', scoreLevels: 'Niveaux de score ordonnés', addLevel: 'Ajouter un niveau', id: 'ID du classificateur', draftQuestions: 'Questions du brouillon', production: 'Production', notDeployed: 'Non déployé', saving: 'Enregistrement…', saveDraft: 'Enregistrer le brouillon', saveHelp: 'L’enregistrement ne modifie pas la production avant le déploiement.', archive: 'Archiver le classificateur', archiveConfirm: 'Archiver « {name} » ? Son endpoint de production sera immédiatement désactivé, mais ses versions et analyses seront conservées.', archivedNotice: 'Classificateur archivé' },
  archive: { overline: 'Cycle de vie', title: 'Classificateurs archivés', description: 'Les classificateurs archivés refusent les appels API et ne comptent plus dans la limite du forfait.', empty: 'Aucun classificateur archivé.', archivedOn: 'Archivé le {date}', restore: 'Restaurer', restoring: 'Restauration…', delete: 'Supprimer définitivement', deleteConfirm: 'Supprimer définitivement « {name} » ? Les versions et la configuration seront irrécupérables. Les analyses historiques agrégées seront conservées.', deleted: 'Classificateur supprimé définitivement', restored: 'Classificateur restauré' },
  actions: { deploying: 'Déploiement…', saveFirst: 'Enregistrez d’abord', deployDraft: 'Déployer le brouillon', upToDate: 'À jour', copied: 'Copié dans le presse-papiers', created: 'Classificateur créé', saved: 'Brouillon enregistré' },
  testing: { overline: 'Banc de test éphémère', title: 'Testez des états réels.', description: 'Testez un état ou séparez plusieurs exemples par une ligne contenant ---. Rien n’est enregistré.', placeholder: 'Collez un état à évaluer…\n\n---\n\nAjoutez un autre état…', running: 'Exécution JEV…', run: 'Lancer le test', emptyTitle: 'Aucun résultat', emptyDescription: 'Testez le brouillon sur des exemples réels avant de le déployer.', state: 'État {number}', confidence: '{value} % de confiance', raw: 'Réponse JEV brute', rawHelp: 'JSON complet et non modifié', copyJson: 'Copier le JSON', trueValue: '{value} % vrai' },
  deployment: { overline: 'Contrôle de production', live: 'La version {version} est en ligne.', empty: 'Aucun déploiement.', description: 'Les déploiements sont des instantanés immuables. Modifier le brouillon ne change jamais la production.', deployCurrent: 'Déployer le brouillon actuel', history: 'Historique', versions: 'Versions disponibles', versionsHelp: 'Sélectionnez un instantané précédent pour revenir en arrière.', versionMeta: '{count} questions · {date}', activate: 'Activer', none: 'Votre premier déploiement apparaîtra ici.', activated: 'La version {version} est active', existingActivated: 'Version existante {version} activée', already: 'Le brouillon est déjà déployé', new: 'Nouvelle version déployée' },
  api: { overline: 'Endpoint de production', title: 'Un état en entrée.', titleEm: 'Des réponses typées en sortie.', description: 'Utilisez l’endpoint géré ou exportez la structure déployée complète pour appeler TypeSafe directement.', studio: 'Via Jev-It Studio', studioHelp: 'Envoyez uniquement l’ID du classificateur et l’état. Le backend résout le déploiement actif.', copyRequest: 'Copier la requête', direct: 'Directement vers TypeSafe', directHelp: 'Une requête portable contenant les questions exactes de la version {version}.', copyInput: 'Copier le JSON d’entrée', copyCurl: 'Copier le cURL', deployToExport: 'Déployez le classificateur pour générer une requête JEV portable.', activeSnapshot: 'Instantané actif :', snapshot: 'Version {version}, déployée {date}', deployBefore: 'Déployez ce classificateur avant d’appeler l’endpoint.', exampleState: 'L’état que JEV doit évaluer' },
  keys: { overline: 'Accès au projet', title: 'Clés API', description: 'Les clés authentifient les appels à vos classificateurs. Les identifiants JEV et OpenAI restent côté serveur.', production: 'Clé de production', none: 'Aucune clé active', created: 'Créée le {date}', generateHelp: 'Générez une clé pour appeler /api/classify.', shownNow: 'Copiez cette clé maintenant — elle ne sera plus affichée.', hashed: 'Stockée sous forme de hash SHA-256', rotate: 'Faire tourner la clé', generate: 'Générer une clé', revoke: 'Révoquer', revokeConfirm: 'Révoquer la clé active ? Les intégrations existantes cesseront de fonctionner.', revoked: 'Clé API révoquée', shownOnce: 'Affichée une fois', shownOnceHelp: 'Le secret en clair est retourné uniquement lors de sa génération.', hashedAtRest: 'Hachée au repos', hashedAtRestHelp: 'MongoDB conserve un condensat SHA-256 irréversible.', instantRotation: 'Rotation immédiate', instantRotationHelp: 'La rotation révoque l’ancienne clé avant de créer la nouvelle.' },
  analytics: { mine: 'Mon espace', platform: 'Plateforme Jev-It', admin: 'Vue administrateur', last30: '30 derniers jours · {scope}', platformTitle: 'Toute la plateforme.', workspaceTitle: 'L’utilisation en un coup d’œil.', platformDescription: 'Activité agrégée de tous les espaces et classificateurs.', workspaceDescription: 'Tous les appels de test et de production, sans conserver les états ni les réponses.', monthlyQuota: 'Quota mensuel', resets: 'Réinitialisation {date}', footprint: 'Empreinte plateforme', workspaces: 'espaces', registeredUsers: '{count} utilisateur inscrit | {count} utilisateurs inscrits', calculating: 'Calcul de l’utilisation…', totalCalls: 'Total des appels', playgroundApi: 'Tests + API', successRate: 'Taux de réussite', failed: '{count} échecs', medianLatency: 'Latence médiane', classifiers: 'Classificateurs', activeFree: 'Actifs en offre gratuite', platformCalls: 'Appels plateforme', allSources: 'Toutes les sources', accounts: 'Comptes', callsOverTime: 'Appels dans le temps', daily: 'Activité quotidienne', timelineEmpty: 'Les appels apparaîtront ici après vos tests et utilisations.', breakdown: 'Répartition', byClassifier: 'Par classificateur', activityEmpty: 'Aucune activité pour le moment.', tenants: 'Espaces', byWorkspace: 'Par espace', totalLabel: '{count} au total', workspacesEmpty: 'Aucun espace.', rowMeta: '{successes} réussis · {latency} ms moy.', workspaceMeta: '{plan} · {classifiers} classificateurs · {successes} réussis' },
}

const ar = {
  common: { workspace: 'مساحة العمل', copy: 'نسخ', active: 'نشط', draft: 'مسودة', live: 'مباشر', questions: 'أسئلة', calls: 'استدعاءات', successful: 'ناجحة', total: 'الإجمالي', signOut: 'تسجيل الخروج', language: 'اللغة' },
  error: { request: 'فشل الطلب.' },
  page: { builder: 'منشئ المصنّفات', keys: 'مفاتيح API', analytics: 'تحليلات الاستخدام', archive: 'الأرشيف' },
  auth: { opening: 'جارٍ فتح Jev-It Studio…', overline: 'مساحة عمل المصنّفات', title: 'ابنِ قراراتك', titleEm: 'من خلال المحادثة.', description: 'سجّل الدخول للاحتفاظ بالمصنّفات وعمليات النشر ومفاتيح API والحصص والتحليلات داخل مساحة عملك الخاصة.', continueGoogle: 'المتابعة باستخدام Google', mongoMissing: 'MongoDB غير متصل.', googleMissing: 'تسجيل Google غير مُعدّ.', check: 'فحص الإعدادات', freeClassifiers: '5 مصنّفات في الخطة المجانية', monthlyCalls: '1,000 استدعاء JEV شهريًا', privateWorkspace: 'خصوصية حسب مساحة العمل' },
  nav: { newClassifier: 'مصنّف جديد', classifiers: 'مصنّفاتك', empty: 'سيظهر مصنّفك الأول هنا.', freePlan: 'الخطة المجانية', archived: 'المصنّفات المؤرشفة' },
  setup: { title: 'صِل MongoDB', titleEm: 'للبدء.', description: 'يخزّن Jev-It Studio المسودات والمحادثات وعمليات النشر ومفاتيح API المشفّرة في MongoDB.', check: 'فحص الاتصال' },
  builder: { overline: 'أنشئ مع Luna', title: 'صِف القرار.', description: 'سيحوّل المساعد احتياجك إلى أسئلة JEV ذرية ومحددة النوع.', architect: 'مهندس JEV', you: 'أنت', placeholder: 'صِف ما الذي يجب أن يقرره المصنّف…', lowReasoning: 'استدلال منخفض', missingKey: 'أضف OPENAI_API_KEY إلى .env', thinking: 'جارٍ التفكير…', send: 'إرسال', liveDraft: 'مسودة مباشرة', updates: 'تتحدث أثناء المحادثة', classifierName: 'اسم المصنّف', purposePending: 'سيتضح الهدف مع استمرار المحادثة.', questionsPending: 'ستظهر أسئلتك محددة النوع هنا.', needsDetail: 'تابع المحادثة — ما زالت هناك تفاصيل ناقصة.', ready: 'جاهز للمراجعة.', creating: 'جارٍ الإنشاء…', create: 'إنشاء المصنّف' },
  classifier: { productionVersion: 'الإنتاج · v{version}', undeployed: 'مسودة غير منشورة', noDescription: 'لا يوجد وصف.', configure: 'الإعداد', test: 'الاختبار', deploy: 'النشر', api: 'API', identity: 'الهوية', identityHelp: 'التفاصيل المقروءة لهذا المصنّف.', name: 'الاسم', description: 'الوصف', contentLanguage: 'لغة المصنّف', contentLanguageHelp: 'تتبع مخرجات المنشئ وتعليمات JEV هذه اللغة.', autoLanguage: 'تلقائي / متعدد اللغات', questions: 'الأسئلة', questionsHelp: 'يُقيّم كل سؤال بشكل مستقل على الحالة نفسها.', addQuestion: 'إضافة سؤال', removeQuestion: 'إزالة السؤال', instructions: 'التعليمات', choiceOptions: 'خيارات الاختيار', addOption: 'إضافة خيار', scoreLevels: 'مستويات التقييم المرتبة', addLevel: 'إضافة مستوى', id: 'معرّف المصنّف', draftQuestions: 'أسئلة المسودة', production: 'الإنتاج', notDeployed: 'غير منشور', saving: 'جارٍ الحفظ…', saveDraft: 'حفظ المسودة', saveHelp: 'لا يؤثر الحفظ في الإنتاج حتى تقوم بالنشر.', archive: 'أرشفة المصنّف', archiveConfirm: 'أرشفة «{name}»؟ سيتوقف endpoint الإنتاجي فورًا مع الاحتفاظ بالإصدارات والتحليلات.', archivedNotice: 'تمت أرشفة المصنّف' },
  archive: { overline: 'دورة حياة المصنّف', title: 'المصنّفات المؤرشفة', description: 'تتوقف المصنّفات المؤرشفة عن قبول استدعاءات API ولا تُحتسب ضمن حد الخطة.', empty: 'لا توجد مصنّفات مؤرشفة.', archivedOn: 'أُرشف في {date}', restore: 'استعادة', restoring: 'جارٍ الاستعادة…', delete: 'حذف نهائي', deleteConfirm: 'حذف «{name}» نهائيًا؟ لا يمكن استرجاع الإصدارات والإعدادات. ستبقى التحليلات التاريخية المجمّعة.', deleted: 'حُذف المصنّف نهائيًا', restored: 'تمت استعادة المصنّف' },
  actions: { deploying: 'جارٍ النشر…', saveFirst: 'احفظ المسودة أولًا', deployDraft: 'نشر المسودة', upToDate: 'محدّث', copied: 'تم النسخ', created: 'تم إنشاء المصنّف', saved: 'تم حفظ المسودة' },
  testing: { overline: 'منصة اختبار مؤقتة', title: 'جرّب حالات حقيقية.', description: 'اختبر حالة واحدة أو افصل أمثلة متعددة بسطر يحتوي على ---. لا يتم حفظ شيء.', placeholder: 'ألصق حالة لتقييمها…\n\n---\n\nأضف حالة أخرى…', running: 'جارٍ تشغيل JEV…', run: 'تشغيل الاختبار', emptyTitle: 'لا توجد نتائج', emptyDescription: 'شغّل المسودة على أمثلة حقيقية قبل نشرها.', state: 'الحالة {number}', confidence: 'ثقة {value}٪', raw: 'استجابة JEV الكاملة', rawHelp: 'JSON كامل دون تعديل', copyJson: 'نسخ JSON', trueValue: 'صحيح بنسبة {value}٪' },
  deployment: { overline: 'التحكم بالإنتاج', live: 'الإصدار {version} مباشر.', empty: 'لم يتم النشر بعد.', description: 'عمليات النشر لقطات ثابتة. تعديل المسودة لا يغيّر مصنّف الإنتاج.', deployCurrent: 'نشر المسودة الحالية', history: 'السجل', versions: 'الإصدارات المتاحة', versionsHelp: 'اختر لقطة سابقة للرجوع إليها.', versionMeta: '{count} أسئلة · {date}', activate: 'تفعيل', none: 'سيظهر أول نشر هنا.', activated: 'الإصدار {version} نشط الآن', existingActivated: 'تم تفعيل الإصدار الموجود {version}', already: 'المسودة منشورة بالفعل', new: 'تم نشر إصدار جديد' },
  api: { overline: 'endpoint الإنتاج', title: 'حالة واحدة تدخل.', titleEm: 'إجابات محددة النوع تخرج.', description: 'استخدم endpoint المُدار أو صدّر البنية المنشورة كاملة لاستدعاء TypeSafe مباشرة.', studio: 'عبر Jev-It Studio', studioHelp: 'أرسل معرّف المصنّف والحالة فقط. يحدد الخادم النشر النشط.', copyRequest: 'نسخ الطلب', direct: 'مباشرة إلى TypeSafe', directHelp: 'طلب قابل للنقل يحتوي الأسئلة الدقيقة من الإصدار {version}.', copyInput: 'نسخ JSON الإدخال', copyCurl: 'نسخ cURL', deployToExport: 'انشر المصنّف لإنشاء طلب JEV قابل للنقل.', activeSnapshot: 'اللقطة النشطة:', snapshot: 'الإصدار {version}، نُشر {date}', deployBefore: 'انشر المصنّف قبل استدعاء endpoint.', exampleState: 'الحالة التي تريد من JEV تقييمها' },
  keys: { overline: 'الوصول للمشروع', title: 'مفاتيح API', description: 'تتحقق المفاتيح من استدعاءات مصنّفاتك. تبقى بيانات JEV وOpenAI على الخادم.', production: 'مفتاح الإنتاج', none: 'لا يوجد مفتاح نشط', created: 'أُنشئ {date}', generateHelp: 'أنشئ مفتاحًا لاستدعاء /api/classify.', shownNow: 'انسخ المفتاح الآن — لن يظهر مجددًا.', hashed: 'مخزّن كتجزئة SHA-256', rotate: 'تدوير المفتاح', generate: 'إنشاء مفتاح', revoke: 'إلغاء', revokeConfirm: 'إلغاء المفتاح النشط؟ ستتوقف التكاملات الحالية.', revoked: 'تم إلغاء مفتاح API', shownOnce: 'يظهر مرة واحدة', shownOnceHelp: 'تُعاد قيمة السر الصريحة عند إنشائه فقط.', hashedAtRest: 'مشفّر عند التخزين', hashedAtRestHelp: 'يخزّن MongoDB تجزئة SHA-256 أحادية الاتجاه.', instantRotation: 'تدوير فوري', instantRotationHelp: 'يلغي التدوير المفتاح القديم قبل إنشاء البديل.' },
  analytics: { mine: 'مساحة عملي', platform: 'منصة Jev-It', admin: 'عرض المدير', last30: 'آخر 30 يومًا · {scope}', platformTitle: 'المنصة بالكامل.', workspaceTitle: 'الاستخدام بنظرة واحدة.', platformDescription: 'نشاط مجمّع عبر جميع المساحات والمصنّفات.', workspaceDescription: 'كل استدعاءات الاختبار والإنتاج دون تخزين الحالات أو الردود.', monthlyQuota: 'الحصة الشهرية', resets: 'إعادة الضبط {date}', footprint: 'حجم المنصة', workspaces: 'مساحات', registeredUsers: 'مستخدم مسجل واحد | {count} مستخدمين مسجلين', calculating: 'جارٍ حساب الاستخدام…', totalCalls: 'إجمالي الاستدعاءات', playgroundApi: 'الاختبار + API', successRate: 'نسبة النجاح', failed: '{count} فاشلة', medianLatency: 'وسيط زمن الاستجابة', classifiers: 'المصنّفات', activeFree: 'نشطة في المجانية', platformCalls: 'استدعاءات المنصة', allSources: 'كل المصادر', accounts: 'الحسابات', callsOverTime: 'الاستدعاءات عبر الزمن', daily: 'النشاط اليومي', timelineEmpty: 'ستظهر الاستدعاءات هنا عند الاختبار والاستخدام.', breakdown: 'التوزيع', byClassifier: 'حسب المصنّف', activityEmpty: 'لا يوجد نشاط بعد.', tenants: 'المساحات', byWorkspace: 'حسب مساحة العمل', totalLabel: 'الإجمالي {count}', workspacesEmpty: 'لا توجد مساحات بعد.', rowMeta: '{successes} ناجحة · متوسط {latency} مللي ثانية', workspaceMeta: '{plan} · {classifiers} مصنّفات · {successes} ناجحة' },
}

const preferred = typeof window === 'undefined' ? 'en' : localStorage.getItem('jev_locale') || navigator.language?.split('-')[0] || 'en'

export const i18n = createI18n({
  legacy: false,
  locale: supportedLocales.some(({ code }) => code === preferred) ? preferred : 'en',
  fallbackLocale: 'en',
  messages: { en, fr, ar },
})
